checks:
  required_workflows:
    codeql.yaml: False
    audit.yaml: False
  versions:
    audit: False

version:
  branch_to_version_re:
    - from: master
      to: latest

publish:
  pypi:
    packages: []
  docker:
    images:
      - name: camptocamp/geoserver