checks:
  required_workflows:
    codeql.yaml: False
    audit.yaml: False
  versions:
    audit: False

#version:
#  branch_to_version_re:
#    - from: ([0-9]+.[0-9]+)
#      to: \1
#    - from: master
#      to: master
#    - from: 7.6-20-04
#      to: 7.6-20-04

publish:
  pypi:
    packages: []
  docker:
    images:
      - name: camptocamp/geoserver