# Config of c2cciutils
# jsonschema of this file : https://github.com/camptocamp/c2cciutils/blob/master/c2cciutils/schema.json

checks:
  required_workflows: False
  black_config: False
  versions: False
  codespell: False
  dependabot_config: False
  editorconfig: False
  prettier: False

# Map GH branches to Dockerhub tags
version:
  branch_to_version_re:
    - from: master
      to: latest
  tag_to_version_re:
    - from: 2.20.1
      to: 2.20.1

publish:
  pypi:
    packages: []
  docker:
    images:
      - name: camptocamp/geoserver